version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SamBookApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cwu4vpavo0j5"
s3_prefix = "SamBookApp"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
