AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-book-app

  Sample SAM Template for sam-book-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

# More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
Resources:
  BookAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: BookAppFunction
      Handler: mybook.BookApp::handleRequest
      Runtime: java11
      MemorySize: 512
      Environment:
        Variables:
          mongoUri: VALUE
          truststore: rds-ca-certsroot.jks
      Events:
        GetBookApp:
          Type: Api
          Properties:
            Path: /books
            Method: get
        PostBookApp:
          Type: Api
          Properties:
            Path: /books
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BookAppdApi:
    Description: "API Gateway endpoint URL for Prod stage for Book App function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/books/"
  BookAppFunction:
    Description: "Book App Lambda Function ARN"
    Value: !GetAtt BookAppFunction.Arn
  BookAppFunctionIamRole:
    Description: "Implicit IAM Role created for Book App function"
    Value: !GetAtt BookAppFunctionRole.Arn
